/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.goodsender.client.api;

import com.goodsender.client.ApiClient;
import com.goodsender.client.ApiException;
import com.goodsender.client.ApiResponse;
import com.goodsender.client.Configuration;
import com.goodsender.client.Pair;

import com.goodsender.client.model.ConsentEmailRequest;
import com.goodsender.client.model.ConsentEmailResult;
import com.goodsender.client.model.EmailAccount;
import com.goodsender.client.model.EmailListResponse;
import com.goodsender.client.model.ErrorResponse;
import com.goodsender.client.model.QuotaExceededError;
import com.goodsender.client.model.SendEmailErrorResponse;
import com.goodsender.client.model.SendEmailRequest;
import com.goodsender.client.model.SendEmailResponse;
import com.goodsender.client.model.TemplateEmailRequest;
import com.goodsender.client.model.TemplateEmailResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class EmailsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EmailsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EmailsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get recipient consent status
   * Retrieve the current consent status for an email address. Optionally filter by sender domain.
   * @param email Email address to look up. (required)
   * @param domain Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)
   * @return List&lt;EmailAccount&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailAccount> getEmailConsentStatus(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String domain) throws ApiException {
    return getEmailConsentStatus(email, domain, null);
  }

  /**
   * Get recipient consent status
   * Retrieve the current consent status for an email address. Optionally filter by sender domain.
   * @param email Email address to look up. (required)
   * @param domain Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)
   * @param headers Optional headers to include in the request
   * @return List&lt;EmailAccount&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailAccount> getEmailConsentStatus(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String domain, Map<String, String> headers) throws ApiException {
    ApiResponse<List<EmailAccount>> localVarResponse = getEmailConsentStatusWithHttpInfo(email, domain, headers);
    return localVarResponse.getData();
  }

  /**
   * Get recipient consent status
   * Retrieve the current consent status for an email address. Optionally filter by sender domain.
   * @param email Email address to look up. (required)
   * @param domain Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)
   * @return ApiResponse&lt;List&lt;EmailAccount&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailAccount>> getEmailConsentStatusWithHttpInfo(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String domain) throws ApiException {
    return getEmailConsentStatusWithHttpInfo(email, domain, null);
  }

  /**
   * Get recipient consent status
   * Retrieve the current consent status for an email address. Optionally filter by sender domain.
   * @param email Email address to look up. (required)
   * @param domain Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;EmailAccount&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailAccount>> getEmailConsentStatusWithHttpInfo(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String domain, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailConsentStatusRequestBuilder(email, domain, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmailConsentStatus", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<EmailAccount>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<EmailAccount> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<EmailAccount>>() {});
        

        return new ApiResponse<List<EmailAccount>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailConsentStatusRequestBuilder(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String domain, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'email' is set
    if (email == null) {
      throw new ApiException(400, "Missing the required parameter 'email' when calling getEmailConsentStatus");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/emails/{email}"
        .replace("{email}", ApiClient.urlEncode(email.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "domain";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("domain", domain));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "goodsender-java/0.1.0");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List email consent statuses
   * Retrieve a paginated list of email consent statuses for a domain.
   * @param domain Sender domain to filter consent records by. (required)
   * @param limit Maximum number of records to return. (optional, default to 50)
   * @param cursor Cursor for pagination. (optional)
   * @param consentStatus Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)
   * @param engagementStatus Status of the recipient&#39;s engagement with the emails. (optional)
   * @return EmailListResponse
   * @throws ApiException if fails to make API call
   */
  public EmailListResponse listEmailConsents(@javax.annotation.Nonnull String domain, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String consentStatus, @javax.annotation.Nullable String engagementStatus) throws ApiException {
    return listEmailConsents(domain, limit, cursor, consentStatus, engagementStatus, null);
  }

  /**
   * List email consent statuses
   * Retrieve a paginated list of email consent statuses for a domain.
   * @param domain Sender domain to filter consent records by. (required)
   * @param limit Maximum number of records to return. (optional, default to 50)
   * @param cursor Cursor for pagination. (optional)
   * @param consentStatus Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)
   * @param engagementStatus Status of the recipient&#39;s engagement with the emails. (optional)
   * @param headers Optional headers to include in the request
   * @return EmailListResponse
   * @throws ApiException if fails to make API call
   */
  public EmailListResponse listEmailConsents(@javax.annotation.Nonnull String domain, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String consentStatus, @javax.annotation.Nullable String engagementStatus, Map<String, String> headers) throws ApiException {
    ApiResponse<EmailListResponse> localVarResponse = listEmailConsentsWithHttpInfo(domain, limit, cursor, consentStatus, engagementStatus, headers);
    return localVarResponse.getData();
  }

  /**
   * List email consent statuses
   * Retrieve a paginated list of email consent statuses for a domain.
   * @param domain Sender domain to filter consent records by. (required)
   * @param limit Maximum number of records to return. (optional, default to 50)
   * @param cursor Cursor for pagination. (optional)
   * @param consentStatus Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)
   * @param engagementStatus Status of the recipient&#39;s engagement with the emails. (optional)
   * @return ApiResponse&lt;EmailListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailListResponse> listEmailConsentsWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String consentStatus, @javax.annotation.Nullable String engagementStatus) throws ApiException {
    return listEmailConsentsWithHttpInfo(domain, limit, cursor, consentStatus, engagementStatus, null);
  }

  /**
   * List email consent statuses
   * Retrieve a paginated list of email consent statuses for a domain.
   * @param domain Sender domain to filter consent records by. (required)
   * @param limit Maximum number of records to return. (optional, default to 50)
   * @param cursor Cursor for pagination. (optional)
   * @param consentStatus Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)
   * @param engagementStatus Status of the recipient&#39;s engagement with the emails. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EmailListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailListResponse> listEmailConsentsWithHttpInfo(@javax.annotation.Nonnull String domain, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String consentStatus, @javax.annotation.Nullable String engagementStatus, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listEmailConsentsRequestBuilder(domain, limit, cursor, consentStatus, engagementStatus, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listEmailConsents", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EmailListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EmailListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EmailListResponse>() {});
        

        return new ApiResponse<EmailListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listEmailConsentsRequestBuilder(@javax.annotation.Nonnull String domain, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String consentStatus, @javax.annotation.Nullable String engagementStatus, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'domain' is set
    if (domain == null) {
      throw new ApiException(400, "Missing the required parameter 'domain' when calling listEmailConsents");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/emails";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "domain";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("domain", domain));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "consentStatus";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("consentStatus", consentStatus));
    localVarQueryParameterBaseName = "engagementStatus";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("engagementStatus", engagementStatus));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "goodsender-java/0.1.0");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Request recipients&#39; consent to receive emails from your domain
   * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
   * @param consentEmailRequest  (required)
   * @return ConsentEmailResult
   * @throws ApiException if fails to make API call
   */
  public ConsentEmailResult requestEmailConsent(@javax.annotation.Nonnull ConsentEmailRequest consentEmailRequest) throws ApiException {
    return requestEmailConsent(consentEmailRequest, null);
  }

  /**
   * Request recipients&#39; consent to receive emails from your domain
   * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
   * @param consentEmailRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ConsentEmailResult
   * @throws ApiException if fails to make API call
   */
  public ConsentEmailResult requestEmailConsent(@javax.annotation.Nonnull ConsentEmailRequest consentEmailRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ConsentEmailResult> localVarResponse = requestEmailConsentWithHttpInfo(consentEmailRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Request recipients&#39; consent to receive emails from your domain
   * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
   * @param consentEmailRequest  (required)
   * @return ApiResponse&lt;ConsentEmailResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ConsentEmailResult> requestEmailConsentWithHttpInfo(@javax.annotation.Nonnull ConsentEmailRequest consentEmailRequest) throws ApiException {
    return requestEmailConsentWithHttpInfo(consentEmailRequest, null);
  }

  /**
   * Request recipients&#39; consent to receive emails from your domain
   * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
   * @param consentEmailRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ConsentEmailResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ConsentEmailResult> requestEmailConsentWithHttpInfo(@javax.annotation.Nonnull ConsentEmailRequest consentEmailRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = requestEmailConsentRequestBuilder(consentEmailRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("requestEmailConsent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ConsentEmailResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ConsentEmailResult responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ConsentEmailResult>() {});
        

        return new ApiResponse<ConsentEmailResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder requestEmailConsentRequestBuilder(@javax.annotation.Nonnull ConsentEmailRequest consentEmailRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'consentEmailRequest' is set
    if (consentEmailRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'consentEmailRequest' when calling requestEmailConsent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/emails/consent";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "goodsender-java/0.1.0");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(consentEmailRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send an email or a batch of emails
   * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
   * @param sendEmailRequest List of emails to send (required)
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendEmail(@javax.annotation.Nonnull SendEmailRequest sendEmailRequest) throws ApiException {
    return sendEmail(sendEmailRequest, null);
  }

  /**
   * Send an email or a batch of emails
   * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
   * @param sendEmailRequest List of emails to send (required)
   * @param headers Optional headers to include in the request
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendEmail(@javax.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SendEmailResponse> localVarResponse = sendEmailWithHttpInfo(sendEmailRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Send an email or a batch of emails
   * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
   * @param sendEmailRequest List of emails to send (required)
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendEmailWithHttpInfo(@javax.annotation.Nonnull SendEmailRequest sendEmailRequest) throws ApiException {
    return sendEmailWithHttpInfo(sendEmailRequest, null);
  }

  /**
   * Send an email or a batch of emails
   * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
   * @param sendEmailRequest List of emails to send (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendEmailWithHttpInfo(@javax.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendEmailRequestBuilder(sendEmailRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SendEmailResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SendEmailResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SendEmailResponse>() {});
        

        return new ApiResponse<SendEmailResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendEmailRequestBuilder(@javax.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sendEmailRequest' is set
    if (sendEmailRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'sendEmailRequest' when calling sendEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/emails/send";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "goodsender-java/0.1.0");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(sendEmailRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send a transactional email using a template
   * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
   * @param templateEmailRequest Template email to send (required)
   * @return TemplateEmailResponse
   * @throws ApiException if fails to make API call
   */
  public TemplateEmailResponse sendTemplateEmail(@javax.annotation.Nonnull TemplateEmailRequest templateEmailRequest) throws ApiException {
    return sendTemplateEmail(templateEmailRequest, null);
  }

  /**
   * Send a transactional email using a template
   * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
   * @param templateEmailRequest Template email to send (required)
   * @param headers Optional headers to include in the request
   * @return TemplateEmailResponse
   * @throws ApiException if fails to make API call
   */
  public TemplateEmailResponse sendTemplateEmail(@javax.annotation.Nonnull TemplateEmailRequest templateEmailRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<TemplateEmailResponse> localVarResponse = sendTemplateEmailWithHttpInfo(templateEmailRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Send a transactional email using a template
   * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
   * @param templateEmailRequest Template email to send (required)
   * @return ApiResponse&lt;TemplateEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TemplateEmailResponse> sendTemplateEmailWithHttpInfo(@javax.annotation.Nonnull TemplateEmailRequest templateEmailRequest) throws ApiException {
    return sendTemplateEmailWithHttpInfo(templateEmailRequest, null);
  }

  /**
   * Send a transactional email using a template
   * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
   * @param templateEmailRequest Template email to send (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TemplateEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TemplateEmailResponse> sendTemplateEmailWithHttpInfo(@javax.annotation.Nonnull TemplateEmailRequest templateEmailRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendTemplateEmailRequestBuilder(templateEmailRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendTemplateEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TemplateEmailResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TemplateEmailResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TemplateEmailResponse>() {});
        

        return new ApiResponse<TemplateEmailResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendTemplateEmailRequestBuilder(@javax.annotation.Nonnull TemplateEmailRequest templateEmailRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'templateEmailRequest' is set
    if (templateEmailRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'templateEmailRequest' when calling sendTemplateEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/emails/template";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");
    localVarRequestBuilder.header("User-Agent", "goodsender-java/0.1.0");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(templateEmailRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
