/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.api;

import com.goodsender.client.ApiException;
import com.goodsender.client.model.DomainListResponse;
import com.goodsender.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DomainsApi
 */
@Disabled
public class DomainsApiTest {

    private final DomainsApi api = new DomainsApi();

    
    /**
     * List domains
     *
     * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDomainsTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        DomainListResponse response = 
        api.listDomains(limit, cursor);
        
        // TODO: test validations
    }
    
}
