/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.api;

import com.goodsender.client.ApiException;
import com.goodsender.client.model.ConsentEmailRequest;
import com.goodsender.client.model.ConsentEmailResult;
import com.goodsender.client.model.EmailAccount;
import com.goodsender.client.model.EmailListResponse;
import com.goodsender.client.model.ErrorResponse;
import com.goodsender.client.model.QuotaExceededError;
import com.goodsender.client.model.SendEmailErrorResponse;
import com.goodsender.client.model.SendEmailRequest;
import com.goodsender.client.model.SendEmailResponse;
import com.goodsender.client.model.TemplateEmailRequest;
import com.goodsender.client.model.TemplateEmailResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for EmailsApi
 */
@Disabled
public class EmailsApiTest {

    private final EmailsApi api = new EmailsApi();

    
    /**
     * Get recipient consent status
     *
     * Retrieve the current consent status for an email address. Optionally filter by sender domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailConsentStatusTest() throws ApiException {
        String email = null;
        String domain = null;
        List<EmailAccount> response = 
        api.getEmailConsentStatus(email, domain);
        
        // TODO: test validations
    }
    
    /**
     * List email consent statuses
     *
     * Retrieve a paginated list of email consent statuses for a domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEmailConsentsTest() throws ApiException {
        String domain = null;
        Integer limit = null;
        String cursor = null;
        String consentStatus = null;
        String engagementStatus = null;
        EmailListResponse response = 
        api.listEmailConsents(domain, limit, cursor, consentStatus, engagementStatus);
        
        // TODO: test validations
    }
    
    /**
     * Request recipients&#39; consent to receive emails from your domain
     *
     * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestEmailConsentTest() throws ApiException {
        ConsentEmailRequest consentEmailRequest = null;
        ConsentEmailResult response = 
        api.requestEmailConsent(consentEmailRequest);
        
        // TODO: test validations
    }
    
    /**
     * Send an email or a batch of emails
     *
     * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendEmailTest() throws ApiException {
        SendEmailRequest sendEmailRequest = null;
        SendEmailResponse response = 
        api.sendEmail(sendEmailRequest);
        
        // TODO: test validations
    }
    
    /**
     * Send a transactional email using a template
     *
     * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTemplateEmailTest() throws ApiException {
        TemplateEmailRequest templateEmailRequest = null;
        TemplateEmailResponse response = 
        api.sendTemplateEmail(templateEmailRequest);
        
        // TODO: test validations
    }
    
}
