/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.DomainVerification;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Domain
 */
class DomainTest {
    private final Domain model = new Domain();

    /**
     * Model tests for Domain
     */
    @Test
    void testDomain() {
        // TODO: test Domain
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'tracking'
     */
    @Test
    void trackingTest() {
        // TODO: test tracking
    }

    /**
     * Test the property 'returnPath'
     */
    @Test
    void returnPathTest() {
        // TODO: test returnPath
    }

    /**
     * Test the property 'requireTls'
     */
    @Test
    void requireTlsTest() {
        // TODO: test requireTls
    }

    /**
     * Test the property 'verification'
     */
    @Test
    void verificationTest() {
        // TODO: test verification
    }

}
