/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DomainVerification
 */
class DomainVerificationTest {
    private final DomainVerification model = new DomainVerification();

    /**
     * Model tests for DomainVerification
     */
    @Test
    void testDomainVerification() {
        // TODO: test DomainVerification
    }

    /**
     * Test the property 'verified'
     */
    @Test
    void verifiedTest() {
        // TODO: test verified
    }

    /**
     * Test the property 'trackingVerified'
     */
    @Test
    void trackingVerifiedTest() {
        // TODO: test trackingVerified
    }

    /**
     * Test the property 'returnPathVerified'
     */
    @Test
    void returnPathVerifiedTest() {
        // TODO: test returnPathVerified
    }

    /**
     * Test the property 'dkim1Verified'
     */
    @Test
    void dkim1VerifiedTest() {
        // TODO: test dkim1Verified
    }

    /**
     * Test the property 'dkim2Verified'
     */
    @Test
    void dkim2VerifiedTest() {
        // TODO: test dkim2Verified
    }

}
