/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.EmailAccount;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmailListResponse
 */
class EmailListResponseTest {
    private final EmailListResponse model = new EmailListResponse();

    /**
     * Model tests for EmailListResponse
     */
    @Test
    void testEmailListResponse() {
        // TODO: test EmailListResponse
    }

    /**
     * Test the property 'emails'
     */
    @Test
    void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    void nextCursorTest() {
        // TODO: test nextCursor
    }

}
