/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuotaExceededError
 */
class QuotaExceededErrorTest {
    private final QuotaExceededError model = new QuotaExceededError();

    /**
     * Model tests for QuotaExceededError
     */
    @Test
    void testQuotaExceededError() {
        // TODO: test QuotaExceededError
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'kind'
     */
    @Test
    void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'limit'
     */
    @Test
    void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'used'
     */
    @Test
    void usedTest() {
        // TODO: test used
    }

    /**
     * Test the property 'resetAt'
     */
    @Test
    void resetAtTest() {
        // TODO: test resetAt
    }

}
