/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.Address;
import com.goodsender.client.model.Attachment;
import com.goodsender.client.model.TrackingSettings;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendEmail
 */
class SendEmailTest {
    private final SendEmail model = new SendEmail();

    /**
     * Model tests for SendEmail
     */
    @Test
    void testSendEmail() {
        // TODO: test SendEmail
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'textContent'
     */
    @Test
    void textContentTest() {
        // TODO: test textContent
    }

    /**
     * Test the property 'htmlContent'
     */
    @Test
    void htmlContentTest() {
        // TODO: test htmlContent
    }

    /**
     * Test the property 'markdownContent'
     */
    @Test
    void markdownContentTest() {
        // TODO: test markdownContent
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'templateData'
     */
    @Test
    void templateDataTest() {
        // TODO: test templateData
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'headers'
     */
    @Test
    void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'replyTo'
     */
    @Test
    void replyToTest() {
        // TODO: test replyTo
    }

    /**
     * Test the property 'sendTime'
     */
    @Test
    void sendTimeTest() {
        // TODO: test sendTime
    }

    /**
     * Test the property 'webhookData'
     */
    @Test
    void webhookDataTest() {
        // TODO: test webhookData
    }

    /**
     * Test the property 'tag'
     */
    @Test
    void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'tracking'
     */
    @Test
    void trackingTest() {
        // TODO: test tracking
    }

}
