/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.Address;
import com.goodsender.client.model.TemplateEmailRequestTemplate;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplateEmailRequest
 */
class TemplateEmailRequestTest {
    private final TemplateEmailRequest model = new TemplateEmailRequest();

    /**
     * Model tests for TemplateEmailRequest
     */
    @Test
    void testTemplateEmailRequest() {
        // TODO: test TemplateEmailRequest
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

}
