/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TrackingSettings
 */
class TrackingSettingsTest {
    private final TrackingSettings model = new TrackingSettings();

    /**
     * Model tests for TrackingSettings
     */
    @Test
    void testTrackingSettings() {
        // TODO: test TrackingSettings
    }

    /**
     * Test the property 'opens'
     */
    @Test
    void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'unsubscribes'
     */
    @Test
    void unsubscribesTest() {
        // TODO: test unsubscribes
    }

    /**
     * Test the property 'unsubscribeGroupId'
     */
    @Test
    void unsubscribeGroupIdTest() {
        // TODO: test unsubscribeGroupId
    }

}
