/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * Either inline_id or file_name is required. Content must be base64 encoded.
 */
@JsonPropertyOrder({
  Attachment.JSON_PROPERTY_FILE_NAME,
  Attachment.JSON_PROPERTY_CONTENT,
  Attachment.JSON_PROPERTY_CONTENT_TYPE,
  Attachment.JSON_PROPERTY_INLINE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class Attachment {
  public static final String JSON_PROPERTY_FILE_NAME = "file_name";
  @javax.annotation.Nullable
  private String fileName = "";

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private byte[] content;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "content_type";
  @javax.annotation.Nonnull
  private String contentType = "";

  public static final String JSON_PROPERTY_INLINE_ID = "inline_id";
  @javax.annotation.Nullable
  private String inlineId = "";

  public Attachment() { 
  }

  public Attachment fileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * File name for the attachment
   * @return fileName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileName() {
    return fileName;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
  }


  public Attachment content(@javax.annotation.Nullable byte[] content) {
    this.content = content;
    return this;
  }

  /**
   * Base64 encoded content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public byte[] getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable byte[] content) {
    this.content = content;
  }


  public Attachment contentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * MIME content type (required)
   * @return contentType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContentType() {
    return contentType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
  }


  public Attachment inlineId(@javax.annotation.Nullable String inlineId) {
    this.inlineId = inlineId;
    return this;
  }

  /**
   * Inline attachment ID
   * @return inlineId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INLINE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInlineId() {
    return inlineId;
  }


  @JsonProperty(value = JSON_PROPERTY_INLINE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInlineId(@javax.annotation.Nullable String inlineId) {
    this.inlineId = inlineId;
  }


  /**
   * Return true if this Attachment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attachment attachment = (Attachment) o;
    return Objects.equals(this.fileName, attachment.fileName) &&
        Arrays.equals(this.content, attachment.content) &&
        Objects.equals(this.contentType, attachment.contentType) &&
        Objects.equals(this.inlineId, attachment.inlineId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, Arrays.hashCode(content), contentType, inlineId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attachment {\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    inlineId: ").append(toIndentedString(inlineId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `file_name` to the URL query string
    if (getFileName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfile_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileName()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `content_type` to the URL query string
    if (getContentType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentType()))));
    }

    // add `inline_id` to the URL query string
    if (getInlineId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinline_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInlineId()))));
    }

    return joiner.toString();
  }
}

