/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.ConsentEmailEntry;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * ConsentEmailRequest
 */
@JsonPropertyOrder({
  ConsentEmailRequest.JSON_PROPERTY_DOMAIN,
  ConsentEmailRequest.JSON_PROPERTY_REDIRECT_URL,
  ConsentEmailRequest.JSON_PROPERTY_EMAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ConsentEmailRequest {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private String domain;

  public static final String JSON_PROPERTY_REDIRECT_URL = "redirect_url";
  @javax.annotation.Nullable
  private String redirectUrl;

  public static final String JSON_PROPERTY_EMAILS = "emails";
  @javax.annotation.Nonnull
  private List<ConsentEmailEntry> emails = new ArrayList<>();

  public ConsentEmailRequest() { 
  }

  public ConsentEmailRequest domain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Domain for the email addresses.
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
  }


  public ConsentEmailRequest redirectUrl(@javax.annotation.Nullable String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

  /**
   * URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient&#39;s email address.
   * @return redirectUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRedirectUrl() {
    return redirectUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectUrl(@javax.annotation.Nullable String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }


  public ConsentEmailRequest emails(@javax.annotation.Nonnull List<ConsentEmailEntry> emails) {
    this.emails = emails;
    return this;
  }

  public ConsentEmailRequest addEmailsItem(ConsentEmailEntry emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * Recipients to request consent from. Each entry may be either a plain email string or a &#x60;{ email, name? }&#x60; object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed. 
   * @return emails
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ConsentEmailEntry> getEmails() {
    return emails;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmails(@javax.annotation.Nonnull List<ConsentEmailEntry> emails) {
    this.emails = emails;
  }


  /**
   * Return true if this ConsentEmailRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentEmailRequest consentEmailRequest = (ConsentEmailRequest) o;
    return Objects.equals(this.domain, consentEmailRequest.domain) &&
        Objects.equals(this.redirectUrl, consentEmailRequest.redirectUrl) &&
        Objects.equals(this.emails, consentEmailRequest.emails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, redirectUrl, emails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentEmailRequest {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `redirect_url` to the URL query string
    if (getRedirectUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sredirect_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedirectUrl()))));
    }

    // add `emails` to the URL query string
    if (getEmails() != null) {
      for (int i = 0; i < getEmails().size(); i++) {
        if (getEmails().get(i) != null) {
          joiner.add(getEmails().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%semails%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

