/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.DomainVerification;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * Domain
 */
@JsonPropertyOrder({
  Domain.JSON_PROPERTY_DOMAIN,
  Domain.JSON_PROPERTY_TRACKING,
  Domain.JSON_PROPERTY_RETURN_PATH,
  Domain.JSON_PROPERTY_REQUIRE_TLS,
  Domain.JSON_PROPERTY_VERIFICATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class Domain {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private String domain;

  public static final String JSON_PROPERTY_TRACKING = "tracking";
  @javax.annotation.Nonnull
  private String tracking;

  public static final String JSON_PROPERTY_RETURN_PATH = "return_path";
  @javax.annotation.Nonnull
  private String returnPath;

  public static final String JSON_PROPERTY_REQUIRE_TLS = "require_tls";
  @javax.annotation.Nonnull
  private Boolean requireTls;

  public static final String JSON_PROPERTY_VERIFICATION = "verification";
  @javax.annotation.Nonnull
  private DomainVerification verification;

  public Domain() { 
  }

  public Domain domain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * The domain name.
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
  }


  public Domain tracking(@javax.annotation.Nonnull String tracking) {
    this.tracking = tracking;
    return this;
  }

  /**
   * Subdomain used for click tracking.
   * @return tracking
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRACKING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTracking() {
    return tracking;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTracking(@javax.annotation.Nonnull String tracking) {
    this.tracking = tracking;
  }


  public Domain returnPath(@javax.annotation.Nonnull String returnPath) {
    this.returnPath = returnPath;
    return this;
  }

  /**
   * Subdomain used for the return path.
   * @return returnPath
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RETURN_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReturnPath() {
    return returnPath;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReturnPath(@javax.annotation.Nonnull String returnPath) {
    this.returnPath = returnPath;
  }


  public Domain requireTls(@javax.annotation.Nonnull Boolean requireTls) {
    this.requireTls = requireTls;
    return this;
  }

  /**
   * Whether outbound mail from this domain must be sent over TLS.
   * @return requireTls
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUIRE_TLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getRequireTls() {
    return requireTls;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRE_TLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequireTls(@javax.annotation.Nonnull Boolean requireTls) {
    this.requireTls = requireTls;
  }


  public Domain verification(@javax.annotation.Nonnull DomainVerification verification) {
    this.verification = verification;
    return this;
  }

  /**
   * Get verification
   * @return verification
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERIFICATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DomainVerification getVerification() {
    return verification;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFICATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerification(@javax.annotation.Nonnull DomainVerification verification) {
    this.verification = verification;
  }


  /**
   * Return true if this Domain object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domain domain = (Domain) o;
    return Objects.equals(this.domain, domain.domain) &&
        Objects.equals(this.tracking, domain.tracking) &&
        Objects.equals(this.returnPath, domain.returnPath) &&
        Objects.equals(this.requireTls, domain.requireTls) &&
        Objects.equals(this.verification, domain.verification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, tracking, returnPath, requireTls, verification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domain {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    tracking: ").append(toIndentedString(tracking)).append("\n");
    sb.append("    returnPath: ").append(toIndentedString(returnPath)).append("\n");
    sb.append("    requireTls: ").append(toIndentedString(requireTls)).append("\n");
    sb.append("    verification: ").append(toIndentedString(verification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `tracking` to the URL query string
    if (getTracking() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stracking%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTracking()))));
    }

    // add `return_path` to the URL query string
    if (getReturnPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreturn_path%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReturnPath()))));
    }

    // add `require_tls` to the URL query string
    if (getRequireTls() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequire_tls%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequireTls()))));
    }

    // add `verification` to the URL query string
    if (getVerification() != null) {
      joiner.add(getVerification().toUrlQueryString(prefix + "verification" + suffix));
    }

    return joiner.toString();
  }
}

