/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * Per-record verification state for the domain. &#x60;verified&#x60; is the overall flag; the individual &#x60;*_verified&#x60; fields indicate which DNS records still need attention when &#x60;verified&#x60; is &#x60;false&#x60;. 
 */
@JsonPropertyOrder({
  DomainVerification.JSON_PROPERTY_VERIFIED,
  DomainVerification.JSON_PROPERTY_TRACKING_VERIFIED,
  DomainVerification.JSON_PROPERTY_RETURN_PATH_VERIFIED,
  DomainVerification.JSON_PROPERTY_DKIM1_VERIFIED,
  DomainVerification.JSON_PROPERTY_DKIM2_VERIFIED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class DomainVerification {
  public static final String JSON_PROPERTY_VERIFIED = "verified";
  @javax.annotation.Nonnull
  private Boolean verified;

  public static final String JSON_PROPERTY_TRACKING_VERIFIED = "tracking_verified";
  @javax.annotation.Nonnull
  private Boolean trackingVerified;

  public static final String JSON_PROPERTY_RETURN_PATH_VERIFIED = "return_path_verified";
  @javax.annotation.Nonnull
  private Boolean returnPathVerified;

  public static final String JSON_PROPERTY_DKIM1_VERIFIED = "dkim1_verified";
  @javax.annotation.Nonnull
  private Boolean dkim1Verified;

  public static final String JSON_PROPERTY_DKIM2_VERIFIED = "dkim2_verified";
  @javax.annotation.Nonnull
  private Boolean dkim2Verified;

  public DomainVerification() { 
  }

  public DomainVerification verified(@javax.annotation.Nonnull Boolean verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Overall verification status. True only when every required DNS record is in place.
   * @return verified
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getVerified() {
    return verified;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerified(@javax.annotation.Nonnull Boolean verified) {
    this.verified = verified;
  }


  public DomainVerification trackingVerified(@javax.annotation.Nonnull Boolean trackingVerified) {
    this.trackingVerified = trackingVerified;
    return this;
  }

  /**
   * Whether the tracking subdomain CNAME is in place.
   * @return trackingVerified
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRACKING_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getTrackingVerified() {
    return trackingVerified;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrackingVerified(@javax.annotation.Nonnull Boolean trackingVerified) {
    this.trackingVerified = trackingVerified;
  }


  public DomainVerification returnPathVerified(@javax.annotation.Nonnull Boolean returnPathVerified) {
    this.returnPathVerified = returnPathVerified;
    return this;
  }

  /**
   * Whether the return-path subdomain CNAME is in place.
   * @return returnPathVerified
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RETURN_PATH_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getReturnPathVerified() {
    return returnPathVerified;
  }


  @JsonProperty(value = JSON_PROPERTY_RETURN_PATH_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReturnPathVerified(@javax.annotation.Nonnull Boolean returnPathVerified) {
    this.returnPathVerified = returnPathVerified;
  }


  public DomainVerification dkim1Verified(@javax.annotation.Nonnull Boolean dkim1Verified) {
    this.dkim1Verified = dkim1Verified;
    return this;
  }

  /**
   * Whether the first DKIM record is in place.
   * @return dkim1Verified
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DKIM1_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getDkim1Verified() {
    return dkim1Verified;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM1_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDkim1Verified(@javax.annotation.Nonnull Boolean dkim1Verified) {
    this.dkim1Verified = dkim1Verified;
  }


  public DomainVerification dkim2Verified(@javax.annotation.Nonnull Boolean dkim2Verified) {
    this.dkim2Verified = dkim2Verified;
    return this;
  }

  /**
   * Whether the second DKIM record is in place.
   * @return dkim2Verified
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DKIM2_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getDkim2Verified() {
    return dkim2Verified;
  }


  @JsonProperty(value = JSON_PROPERTY_DKIM2_VERIFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDkim2Verified(@javax.annotation.Nonnull Boolean dkim2Verified) {
    this.dkim2Verified = dkim2Verified;
  }


  /**
   * Return true if this DomainVerification object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainVerification domainVerification = (DomainVerification) o;
    return Objects.equals(this.verified, domainVerification.verified) &&
        Objects.equals(this.trackingVerified, domainVerification.trackingVerified) &&
        Objects.equals(this.returnPathVerified, domainVerification.returnPathVerified) &&
        Objects.equals(this.dkim1Verified, domainVerification.dkim1Verified) &&
        Objects.equals(this.dkim2Verified, domainVerification.dkim2Verified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verified, trackingVerified, returnPathVerified, dkim1Verified, dkim2Verified);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainVerification {\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    trackingVerified: ").append(toIndentedString(trackingVerified)).append("\n");
    sb.append("    returnPathVerified: ").append(toIndentedString(returnPathVerified)).append("\n");
    sb.append("    dkim1Verified: ").append(toIndentedString(dkim1Verified)).append("\n");
    sb.append("    dkim2Verified: ").append(toIndentedString(dkim2Verified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `verified` to the URL query string
    if (getVerified() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverified%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerified()))));
    }

    // add `tracking_verified` to the URL query string
    if (getTrackingVerified() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stracking_verified%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTrackingVerified()))));
    }

    // add `return_path_verified` to the URL query string
    if (getReturnPathVerified() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreturn_path_verified%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReturnPathVerified()))));
    }

    // add `dkim1_verified` to the URL query string
    if (getDkim1Verified() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim1_verified%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkim1Verified()))));
    }

    // add `dkim2_verified` to the URL query string
    if (getDkim2Verified() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdkim2_verified%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDkim2Verified()))));
    }

    return joiner.toString();
  }
}

