/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * EmailAccount
 */
@JsonPropertyOrder({
  EmailAccount.JSON_PROPERTY_EMAIL,
  EmailAccount.JSON_PROPERTY_NAME,
  EmailAccount.JSON_PROPERTY_DOMAIN,
  EmailAccount.JSON_PROPERTY_CONSENT_STATUS,
  EmailAccount.JSON_PROPERTY_ENGAGEMENT_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class EmailAccount {
  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nonnull
  private String email;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nonnull
  private String domain;

  /**
   * Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.
   */
  public enum ConsentStatusEnum {
    PENDING(String.valueOf("pending")),
    
    REQUESTED(String.valueOf("requested")),
    
    FAILED(String.valueOf("failed")),
    
    GRANTED(String.valueOf("granted")),
    
    DENIED(String.valueOf("denied"));

    private String value;

    ConsentStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ConsentStatusEnum fromValue(String value) {
      for (ConsentStatusEnum b : ConsentStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONSENT_STATUS = "consentStatus";
  @javax.annotation.Nonnull
  private ConsentStatusEnum consentStatus;

  /**
   * Status of the recipient&#39;s engagement with the emails.
   */
  public enum EngagementStatusEnum {
    NEW(String.valueOf("new")),
    
    HOT(String.valueOf("hot")),
    
    WARM(String.valueOf("warm")),
    
    COOLING(String.valueOf("cooling")),
    
    DORMANT(String.valueOf("dormant")),
    
    INACTIVE(String.valueOf("inactive"));

    private String value;

    EngagementStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EngagementStatusEnum fromValue(String value) {
      for (EngagementStatusEnum b : EngagementStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENGAGEMENT_STATUS = "engagementStatus";
  @javax.annotation.Nullable
  private EngagementStatusEnum engagementStatus;

  public EmailAccount() { 
  }

  public EmailAccount email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Recipient email address.
   * @return email
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public EmailAccount name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public EmailAccount domain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Domain part of the email address.
   * @return domain
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomain(@javax.annotation.Nonnull String domain) {
    this.domain = domain;
  }


  public EmailAccount consentStatus(@javax.annotation.Nonnull ConsentStatusEnum consentStatus) {
    this.consentStatus = consentStatus;
    return this;
  }

  /**
   * Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.
   * @return consentStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONSENT_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ConsentStatusEnum getConsentStatus() {
    return consentStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsentStatus(@javax.annotation.Nonnull ConsentStatusEnum consentStatus) {
    this.consentStatus = consentStatus;
  }


  public EmailAccount engagementStatus(@javax.annotation.Nullable EngagementStatusEnum engagementStatus) {
    this.engagementStatus = engagementStatus;
    return this;
  }

  /**
   * Status of the recipient&#39;s engagement with the emails.
   * @return engagementStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENGAGEMENT_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EngagementStatusEnum getEngagementStatus() {
    return engagementStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_ENGAGEMENT_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEngagementStatus(@javax.annotation.Nullable EngagementStatusEnum engagementStatus) {
    this.engagementStatus = engagementStatus;
  }


  /**
   * Return true if this EmailAccount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailAccount emailAccount = (EmailAccount) o;
    return Objects.equals(this.email, emailAccount.email) &&
        equalsNullable(this.name, emailAccount.name) &&
        Objects.equals(this.domain, emailAccount.domain) &&
        Objects.equals(this.consentStatus, emailAccount.consentStatus) &&
        Objects.equals(this.engagementStatus, emailAccount.engagementStatus);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, hashCodeNullable(name), domain, consentStatus, engagementStatus);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailAccount {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    consentStatus: ").append(toIndentedString(consentStatus)).append("\n");
    sb.append("    engagementStatus: ").append(toIndentedString(engagementStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `consentStatus` to the URL query string
    if (getConsentStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconsentStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentStatus()))));
    }

    // add `engagementStatus` to the URL query string
    if (getEngagementStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sengagementStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEngagementStatus()))));
    }

    return joiner.toString();
  }
}

