/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * QuotaExceededError
 */
@JsonPropertyOrder({
  QuotaExceededError.JSON_PROPERTY_CODE,
  QuotaExceededError.JSON_PROPERTY_KIND,
  QuotaExceededError.JSON_PROPERTY_MESSAGE,
  QuotaExceededError.JSON_PROPERTY_LIMIT,
  QuotaExceededError.JSON_PROPERTY_USED,
  QuotaExceededError.JSON_PROPERTY_RESET_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class QuotaExceededError {
  /**
   * Machine-readable error code.
   */
  public enum CodeEnum {
    QUOTA_EXCEEDED(String.valueOf("quota_exceeded"));

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private CodeEnum code;

  /**
   * Whether the daily or monthly quota was exhausted.
   */
  public enum KindEnum {
    DAILY(String.valueOf("daily")),
    
    MONTHLY(String.valueOf("monthly"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nonnull
  private KindEnum kind;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_USED = "used";
  @javax.annotation.Nonnull
  private Integer used;

  public static final String JSON_PROPERTY_RESET_AT = "resetAt";
  @javax.annotation.Nonnull
  private OffsetDateTime resetAt;

  public QuotaExceededError() { 
  }

  public QuotaExceededError code(@javax.annotation.Nonnull CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Machine-readable error code.
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CodeEnum getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull CodeEnum code) {
    this.code = code;
  }


  public QuotaExceededError kind(@javax.annotation.Nonnull KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Whether the daily or monthly quota was exhausted.
   * @return kind
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKind(@javax.annotation.Nonnull KindEnum kind) {
    this.kind = kind;
  }


  public QuotaExceededError message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Human-readable error message.
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }


  public QuotaExceededError limit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Quota limit that was reached.
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public QuotaExceededError used(@javax.annotation.Nonnull Integer used) {
    this.used = used;
    return this;
  }

  /**
   * Number of emails already used against the quota.
   * @return used
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getUsed() {
    return used;
  }


  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsed(@javax.annotation.Nonnull Integer used) {
    this.used = used;
  }


  public QuotaExceededError resetAt(@javax.annotation.Nonnull OffsetDateTime resetAt) {
    this.resetAt = resetAt;
    return this;
  }

  /**
   * Timestamp at which the quota window resets.
   * @return resetAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESET_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getResetAt() {
    return resetAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RESET_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResetAt(@javax.annotation.Nonnull OffsetDateTime resetAt) {
    this.resetAt = resetAt;
  }


  /**
   * Return true if this QuotaExceededError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotaExceededError quotaExceededError = (QuotaExceededError) o;
    return Objects.equals(this.code, quotaExceededError.code) &&
        Objects.equals(this.kind, quotaExceededError.kind) &&
        Objects.equals(this.message, quotaExceededError.message) &&
        Objects.equals(this.limit, quotaExceededError.limit) &&
        Objects.equals(this.used, quotaExceededError.used) &&
        Objects.equals(this.resetAt, quotaExceededError.resetAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, kind, message, limit, used, resetAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotaExceededError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    resetAt: ").append(toIndentedString(resetAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `used` to the URL query string
    if (getUsed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sused%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsed()))));
    }

    // add `resetAt` to the URL query string
    if (getResetAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresetAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResetAt()))));
    }

    return joiner.toString();
  }
}

