/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * SendEmailResponse
 */
@JsonPropertyOrder({
  SendEmailResponse.JSON_PROPERTY_SENT,
  SendEmailResponse.JSON_PROPERTY_DECLINED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class SendEmailResponse {
  public static final String JSON_PROPERTY_SENT = "sent";
  @javax.annotation.Nonnull
  private Integer sent;

  public static final String JSON_PROPERTY_DECLINED = "declined";
  @javax.annotation.Nonnull
  private Integer declined;

  public SendEmailResponse() { 
  }

  public SendEmailResponse sent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
    return this;
  }

  /**
   * Number of emails sent (recipients had consent allowing delivery)
   * @return sent
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getSent() {
    return sent;
  }


  @JsonProperty(value = JSON_PROPERTY_SENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
  }


  public SendEmailResponse declined(@javax.annotation.Nonnull Integer declined) {
    this.declined = declined;
    return this;
  }

  /**
   * Number of emails not sent because recipients did not have granted consent to receive emails
   * @return declined
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DECLINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDeclined() {
    return declined;
  }


  @JsonProperty(value = JSON_PROPERTY_DECLINED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeclined(@javax.annotation.Nonnull Integer declined) {
    this.declined = declined;
  }


  /**
   * Return true if this SendEmailResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendEmailResponse sendEmailResponse = (SendEmailResponse) o;
    return Objects.equals(this.sent, sendEmailResponse.sent) &&
        Objects.equals(this.declined, sendEmailResponse.declined);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sent, declined);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendEmailResponse {\n");
    sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
    sb.append("    declined: ").append(toIndentedString(declined)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sent` to the URL query string
    if (getSent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSent()))));
    }

    // add `declined` to the URL query string
    if (getDeclined() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeclined%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeclined()))));
    }

    return joiner.toString();
  }
}

