/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.Address;
import com.goodsender.client.model.Attachment;
import com.goodsender.client.model.TrackingSettings;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * Must provide valid sender and subject. At least one recipient (from &#39;to&#39;, &#39;cc&#39;, or &#39;bcc&#39;) is required. Either &#39;text_content&#39;, &#39;html_content&#39;, &#39;markdown_content&#39;, or &#39;template_id&#39; is required. When &#39;markdown_content&#39; is provided, &#39;text_content&#39; and &#39;html_content&#39; are ignored. 
 */
@JsonPropertyOrder({
  SendEmail.JSON_PROPERTY_FROM,
  SendEmail.JSON_PROPERTY_TO,
  SendEmail.JSON_PROPERTY_SUBJECT,
  SendEmail.JSON_PROPERTY_TEXT_CONTENT,
  SendEmail.JSON_PROPERTY_HTML_CONTENT,
  SendEmail.JSON_PROPERTY_MARKDOWN_CONTENT,
  SendEmail.JSON_PROPERTY_TEMPLATE_ID,
  SendEmail.JSON_PROPERTY_TEMPLATE_DATA,
  SendEmail.JSON_PROPERTY_ATTACHMENTS,
  SendEmail.JSON_PROPERTY_HEADERS,
  SendEmail.JSON_PROPERTY_REPLY_TO,
  SendEmail.JSON_PROPERTY_SEND_TIME,
  SendEmail.JSON_PROPERTY_WEBHOOK_DATA,
  SendEmail.JSON_PROPERTY_TAG,
  SendEmail.JSON_PROPERTY_TRACKING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class SendEmail {
  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private Address from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private List<Address> to = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject = "";

  public static final String JSON_PROPERTY_TEXT_CONTENT = "text_content";
  @javax.annotation.Nullable
  private String textContent;

  public static final String JSON_PROPERTY_HTML_CONTENT = "html_content";
  @javax.annotation.Nullable
  private String htmlContent;

  public static final String JSON_PROPERTY_MARKDOWN_CONTENT = "markdown_content";
  @javax.annotation.Nullable
  private String markdownContent;

  public static final String JSON_PROPERTY_TEMPLATE_ID = "template_id";
  @javax.annotation.Nullable
  private String templateId;

  public static final String JSON_PROPERTY_TEMPLATE_DATA = "template_data";
  @javax.annotation.Nullable
  private Map<String, Object> templateData = new HashMap<>();

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @javax.annotation.Nullable
  private List<Attachment> attachments = new ArrayList<>();

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @javax.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_REPLY_TO = "reply_to";
  @javax.annotation.Nullable
  private Address replyTo;

  public static final String JSON_PROPERTY_SEND_TIME = "send_time";
  @javax.annotation.Nullable
  private Long sendTime;

  public static final String JSON_PROPERTY_WEBHOOK_DATA = "webhook_data";
  @javax.annotation.Nullable
  private Map<String, String> webhookData = new HashMap<>();

  public static final String JSON_PROPERTY_TAG = "tag";
  @javax.annotation.Nullable
  private String tag;

  public static final String JSON_PROPERTY_TRACKING = "tracking";
  @javax.annotation.Nullable
  private TrackingSettings tracking;

  public SendEmail() { 
  }

  public SendEmail from(@javax.annotation.Nonnull Address from) {
    this.from = from;
    return this;
  }

  /**
   * Sender address (required)
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Address getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull Address from) {
    this.from = from;
  }


  public SendEmail to(@javax.annotation.Nonnull List<Address> to) {
    this.to = to;
    return this;
  }

  public SendEmail addToItem(Address toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

  /**
   * To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Address> getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull List<Address> to) {
    this.to = to;
  }


  public SendEmail subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * The subject of the email (required)
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public SendEmail textContent(@javax.annotation.Nullable String textContent) {
    this.textContent = textContent;
    return this;
  }

  /**
   * Plain text content
   * @return textContent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTextContent() {
    return textContent;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextContent(@javax.annotation.Nullable String textContent) {
    this.textContent = textContent;
  }


  public SendEmail htmlContent(@javax.annotation.Nullable String htmlContent) {
    this.htmlContent = htmlContent;
    return this;
  }

  /**
   * HTML content
   * @return htmlContent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HTML_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHtmlContent() {
    return htmlContent;
  }


  @JsonProperty(value = JSON_PROPERTY_HTML_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHtmlContent(@javax.annotation.Nullable String htmlContent) {
    this.htmlContent = htmlContent;
  }


  public SendEmail markdownContent(@javax.annotation.Nullable String markdownContent) {
    this.markdownContent = markdownContent;
    return this;
  }

  /**
   * Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. 
   * @return markdownContent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKDOWN_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarkdownContent() {
    return markdownContent;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKDOWN_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkdownContent(@javax.annotation.Nullable String markdownContent) {
    this.markdownContent = markdownContent;
  }


  public SendEmail templateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * Template ID for templated emails
   * @return templateId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTemplateId() {
    return templateId;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateId(@javax.annotation.Nullable String templateId) {
    this.templateId = templateId;
  }


  public SendEmail templateData(@javax.annotation.Nullable Map<String, Object> templateData) {
    this.templateData = templateData;
    return this;
  }

  public SendEmail putTemplateDataItem(String key, Object templateDataItem) {
    if (this.templateData == null) {
      this.templateData = new HashMap<>();
    }
    this.templateData.put(key, templateDataItem);
    return this;
  }

  /**
   * Data to populate template variables
   * @return templateData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_DATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getTemplateData() {
    return templateData;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_DATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateData(@javax.annotation.Nullable Map<String, Object> templateData) {
    this.templateData = templateData;
  }


  public SendEmail attachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public SendEmail addAttachmentsItem(Attachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

  /**
   * Email attachments
   * @return attachments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Attachment> getAttachments() {
    return attachments;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
  }


  public SendEmail headers(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public SendEmail putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Custom email headers
   * @return headers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@javax.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }


  public SendEmail replyTo(@javax.annotation.Nullable Address replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Reply-to address
   * @return replyTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Address getReplyTo() {
    return replyTo;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyTo(@javax.annotation.Nullable Address replyTo) {
    this.replyTo = replyTo;
  }


  public SendEmail sendTime(@javax.annotation.Nullable Long sendTime) {
    this.sendTime = sendTime;
    return this;
  }

  /**
   * Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
   * @return sendTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEND_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getSendTime() {
    return sendTime;
  }


  @JsonProperty(value = JSON_PROPERTY_SEND_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendTime(@javax.annotation.Nullable Long sendTime) {
    this.sendTime = sendTime;
  }


  public SendEmail webhookData(@javax.annotation.Nullable Map<String, String> webhookData) {
    this.webhookData = webhookData;
    return this;
  }

  public SendEmail putWebhookDataItem(String key, String webhookDataItem) {
    if (this.webhookData == null) {
      this.webhookData = new HashMap<>();
    }
    this.webhookData.put(key, webhookDataItem);
    return this;
  }

  /**
   * Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
   * @return webhookData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getWebhookData() {
    return webhookData;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookData(@javax.annotation.Nullable Map<String, String> webhookData) {
    this.webhookData = webhookData;
  }


  public SendEmail tag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Custom tag for tracking. Maximum 100 characters.
   * @return tag
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public SendEmail tracking(@javax.annotation.Nullable TrackingSettings tracking) {
    this.tracking = tracking;
    return this;
  }

  /**
   * Email tracking settings
   * @return tracking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TrackingSettings getTracking() {
    return tracking;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTracking(@javax.annotation.Nullable TrackingSettings tracking) {
    this.tracking = tracking;
  }


  /**
   * Return true if this SendEmail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendEmail sendEmail = (SendEmail) o;
    return Objects.equals(this.from, sendEmail.from) &&
        Objects.equals(this.to, sendEmail.to) &&
        Objects.equals(this.subject, sendEmail.subject) &&
        Objects.equals(this.textContent, sendEmail.textContent) &&
        Objects.equals(this.htmlContent, sendEmail.htmlContent) &&
        Objects.equals(this.markdownContent, sendEmail.markdownContent) &&
        Objects.equals(this.templateId, sendEmail.templateId) &&
        Objects.equals(this.templateData, sendEmail.templateData) &&
        Objects.equals(this.attachments, sendEmail.attachments) &&
        Objects.equals(this.headers, sendEmail.headers) &&
        Objects.equals(this.replyTo, sendEmail.replyTo) &&
        Objects.equals(this.sendTime, sendEmail.sendTime) &&
        Objects.equals(this.webhookData, sendEmail.webhookData) &&
        Objects.equals(this.tag, sendEmail.tag) &&
        Objects.equals(this.tracking, sendEmail.tracking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, subject, textContent, htmlContent, markdownContent, templateId, templateData, attachments, headers, replyTo, sendTime, webhookData, tag, tracking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendEmail {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    textContent: ").append(toIndentedString(textContent)).append("\n");
    sb.append("    htmlContent: ").append(toIndentedString(htmlContent)).append("\n");
    sb.append("    markdownContent: ").append(toIndentedString(markdownContent)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    templateData: ").append(toIndentedString(templateData)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    sendTime: ").append(toIndentedString(sendTime)).append("\n");
    sb.append("    webhookData: ").append(toIndentedString(webhookData)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    tracking: ").append(toIndentedString(tracking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(getFrom().toUrlQueryString(prefix + "from" + suffix));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      for (int i = 0; i < getTo().size(); i++) {
        if (getTo().get(i) != null) {
          joiner.add(getTo().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sto%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `text_content` to the URL query string
    if (getTextContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stext_content%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTextContent()))));
    }

    // add `html_content` to the URL query string
    if (getHtmlContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shtml_content%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHtmlContent()))));
    }

    // add `markdown_content` to the URL query string
    if (getMarkdownContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarkdown_content%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarkdownContent()))));
    }

    // add `template_id` to the URL query string
    if (getTemplateId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateId()))));
    }

    // add `template_data` to the URL query string
    if (getTemplateData() != null) {
      for (String _key : getTemplateData().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_data%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getTemplateData().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getTemplateData().get(_key)))));
      }
    }

    // add `attachments` to the URL query string
    if (getAttachments() != null) {
      for (int i = 0; i < getAttachments().size(); i++) {
        if (getAttachments().get(i) != null) {
          joiner.add(getAttachments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sattachments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `reply_to` to the URL query string
    if (getReplyTo() != null) {
      joiner.add(getReplyTo().toUrlQueryString(prefix + "reply_to" + suffix));
    }

    // add `send_time` to the URL query string
    if (getSendTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssend_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSendTime()))));
    }

    // add `webhook_data` to the URL query string
    if (getWebhookData() != null) {
      for (String _key : getWebhookData().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%swebhook_data%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getWebhookData().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getWebhookData().get(_key)))));
      }
    }

    // add `tag` to the URL query string
    if (getTag() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stag%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTag()))));
    }

    // add `tracking` to the URL query string
    if (getTracking() != null) {
      joiner.add(getTracking().toUrlQueryString(prefix + "tracking" + suffix));
    }

    return joiner.toString();
  }
}

