/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.goodsender.client.model.Address;
import com.goodsender.client.model.TemplateEmailRequestTemplate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * TemplateEmailRequest
 */
@JsonPropertyOrder({
  TemplateEmailRequest.JSON_PROPERTY_FROM,
  TemplateEmailRequest.JSON_PROPERTY_TO,
  TemplateEmailRequest.JSON_PROPERTY_SUBJECT,
  TemplateEmailRequest.JSON_PROPERTY_TEMPLATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TemplateEmailRequest {
  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private Address from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private Address to;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_TEMPLATE = "template";
  @javax.annotation.Nonnull
  private TemplateEmailRequestTemplate template;

  public TemplateEmailRequest() { 
  }

  public TemplateEmailRequest from(@javax.annotation.Nonnull Address from) {
    this.from = from;
    return this;
  }

  /**
   * Sender address (required)
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Address getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull Address from) {
    this.from = from;
  }


  public TemplateEmailRequest to(@javax.annotation.Nonnull Address to) {
    this.to = to;
    return this;
  }

  /**
   * Recipient address (required)
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Address getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull Address to) {
    this.to = to;
  }


  public TemplateEmailRequest subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * The subject of the email (required)
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public TemplateEmailRequest template(@javax.annotation.Nonnull TemplateEmailRequestTemplate template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TemplateEmailRequestTemplate getTemplate() {
    return template;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplate(@javax.annotation.Nonnull TemplateEmailRequestTemplate template) {
    this.template = template;
  }


  /**
   * Return true if this TemplateEmailRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateEmailRequest templateEmailRequest = (TemplateEmailRequest) o;
    return Objects.equals(this.from, templateEmailRequest.from) &&
        Objects.equals(this.to, templateEmailRequest.to) &&
        Objects.equals(this.subject, templateEmailRequest.subject) &&
        Objects.equals(this.template, templateEmailRequest.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, subject, template);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateEmailRequest {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(getFrom().toUrlQueryString(prefix + "from" + suffix));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(getTo().toUrlQueryString(prefix + "to" + suffix));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `template` to the URL query string
    if (getTemplate() != null) {
      joiner.add(getTemplate().toUrlQueryString(prefix + "template" + suffix));
    }

    return joiner.toString();
  }
}

