/*
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.goodsender.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.goodsender.client.ApiClient;
/**
 * Controls email tracking and unsubscribe settings
 */
@JsonPropertyOrder({
  TrackingSettings.JSON_PROPERTY_OPENS,
  TrackingSettings.JSON_PROPERTY_CLICKS,
  TrackingSettings.JSON_PROPERTY_UNSUBSCRIBES,
  TrackingSettings.JSON_PROPERTY_UNSUBSCRIBE_GROUP_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TrackingSettings {
  public static final String JSON_PROPERTY_OPENS = "opens";
  @javax.annotation.Nullable
  private Boolean opens;

  public static final String JSON_PROPERTY_CLICKS = "clicks";
  @javax.annotation.Nullable
  private Boolean clicks;

  public static final String JSON_PROPERTY_UNSUBSCRIBES = "unsubscribes";
  @javax.annotation.Nullable
  private Boolean unsubscribes;

  public static final String JSON_PROPERTY_UNSUBSCRIBE_GROUP_ID = "unsubscribe_group_id";
  private JsonNullable<Long> unsubscribeGroupId = JsonNullable.<Long>undefined();

  public TrackingSettings() { 
  }

  public TrackingSettings opens(@javax.annotation.Nullable Boolean opens) {
    this.opens = opens;
    return this;
  }

  /**
   * Whether to track email opens
   * @return opens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOpens() {
    return opens;
  }


  @JsonProperty(value = JSON_PROPERTY_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpens(@javax.annotation.Nullable Boolean opens) {
    this.opens = opens;
  }


  public TrackingSettings clicks(@javax.annotation.Nullable Boolean clicks) {
    this.clicks = clicks;
    return this;
  }

  /**
   * Whether to track link clicks
   * @return clicks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLICKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getClicks() {
    return clicks;
  }


  @JsonProperty(value = JSON_PROPERTY_CLICKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClicks(@javax.annotation.Nullable Boolean clicks) {
    this.clicks = clicks;
  }


  public TrackingSettings unsubscribes(@javax.annotation.Nullable Boolean unsubscribes) {
    this.unsubscribes = unsubscribes;
    return this;
  }

  /**
   * Whether to track unsubscribes
   * @return unsubscribes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUnsubscribes() {
    return unsubscribes;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsubscribes(@javax.annotation.Nullable Boolean unsubscribes) {
    this.unsubscribes = unsubscribes;
  }


  public TrackingSettings unsubscribeGroupId(@javax.annotation.Nullable Long unsubscribeGroupId) {
    this.unsubscribeGroupId = JsonNullable.<Long>of(unsubscribeGroupId);
    return this;
  }

  /**
   * Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.
   * @return unsubscribeGroupId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Long getUnsubscribeGroupId() {
        return unsubscribeGroupId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getUnsubscribeGroupId_JsonNullable() {
    return unsubscribeGroupId;
  }
  
  @JsonProperty(JSON_PROPERTY_UNSUBSCRIBE_GROUP_ID)
  public void setUnsubscribeGroupId_JsonNullable(JsonNullable<Long> unsubscribeGroupId) {
    this.unsubscribeGroupId = unsubscribeGroupId;
  }

  public void setUnsubscribeGroupId(@javax.annotation.Nullable Long unsubscribeGroupId) {
    this.unsubscribeGroupId = JsonNullable.<Long>of(unsubscribeGroupId);
  }


  /**
   * Return true if this TrackingSettings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingSettings trackingSettings = (TrackingSettings) o;
    return Objects.equals(this.opens, trackingSettings.opens) &&
        Objects.equals(this.clicks, trackingSettings.clicks) &&
        Objects.equals(this.unsubscribes, trackingSettings.unsubscribes) &&
        equalsNullable(this.unsubscribeGroupId, trackingSettings.unsubscribeGroupId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(opens, clicks, unsubscribes, hashCodeNullable(unsubscribeGroupId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingSettings {\n");
    sb.append("    opens: ").append(toIndentedString(opens)).append("\n");
    sb.append("    clicks: ").append(toIndentedString(clicks)).append("\n");
    sb.append("    unsubscribes: ").append(toIndentedString(unsubscribes)).append("\n");
    sb.append("    unsubscribeGroupId: ").append(toIndentedString(unsubscribeGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `opens` to the URL query string
    if (getOpens() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpens()))));
    }

    // add `clicks` to the URL query string
    if (getClicks() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclicks%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClicks()))));
    }

    // add `unsubscribes` to the URL query string
    if (getUnsubscribes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribes()))));
    }

    // add `unsubscribe_group_id` to the URL query string
    if (getUnsubscribeGroupId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribe_group_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribeGroupId()))));
    }

    return joiner.toString();
  }
}

